name: Pykern Tests
on: [pull_request]
env:
  PYKERN_TEST_CI: 1
jobs:
  Explore-GitHub-Actions:
    container: radiasoft/sirepo:latest
    runs-on: ubuntu-latest
    steps:
      - run: |
          export PYKERN_TEST_CI_GITHUB_SERVER_URL=$GITHUB_SERVER_URL
          export PYKERN_TEST_CI_GITHUB_REPOSITORY=$GITHUB_REPOSITORY
          export PYKERN_TEST_CI_BRANCH=$GITHUB_HEAD_REF
          source /rsentry
          cd $HOME
          git clone "$PYKERN_TEST_CI_GITHUB_SERVER_URL/$PYKERN_TEST_CI_GITHUB_REPOSITORY"
          cd pykern
          git checkout $PYKERN_TEST_CI_BRANCH
          git pull
          pip install -e .
          pykern test
        name: Run in container