name: ci-pull-request
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      - main
      - master

jobs:
  ci-pull-request:
    if: ${{ github.event.pull_request.merged == true || github.event.action != 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo $GITHUB_SHA
      - run: |
          echo ${{github.event.pull_request.head.sha}}
      - run: |
          echo "${{ github.event.action }}"
      - run: |
          git log
      - run: |
          pwd
      - run: |
          ls