name: ci-pull-request
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      - main
      - master

jobs:
  ci-pull-request:
    if: ${{ github.event.action != 'closed' || github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl -LsS https://radia.run | bash -s ci-pull-request
